### ISSUE TITLE
Include automatic data and events cleaning on empty

### ISSUE THREAD

**Issue by gpetrov** [vitmalina/mquery#1]
A great feature of jQuery when dealing with memory leaks was that it automatically cleaned data attributes and event listeners when nodes are removed or emptied.

Could you add this also to the empty and other dom node cleaning methods in this library?

**Comment by vitmalina** [comment]
Isn't it what garbage collector does automatically? If you calls html's `node.remove()`, the node is deleted and unless it is stored in some var, it will be garbage collected on its own. Do you have any articles to read about it?

**Comment by vitmalina** [comment]
I investigated a bit more and I think it is all good. mQuery stores additional data on the node itself, and it is it removed from the dome, the data is freed too. So, I do not think anything else is needed.

Please comment if I am wrong, otherwise, I will close it within a few weeks.

**Comment by gpetrov** [comment]
You are right modern browser clean up well, as long as you are not assigning a global function as event handler otherwise reference is kept and node is not garbage collected.
