### ISSUE TITLE
Show / Hide should remember and restore original display value

### ISSUE THREAD

**Issue by mpf82** [vitmalina/mquery#4]
JQuery and Cash store the original display value and restore it again correctly.

Currently mQuery sets the display value to ``none/inherit``, which can often be wrong, e.g. if the original display value was ``flex`` or ``hidden``.

JQuery uses some sort of private cache: https://github.com/jquery/jquery/blob/a684e6ba836f7c553968d7d026ed7941e1a612d8/src/css/showHide.js

Cash uses some combination of storing the display value in a ``___cd`` property on the element and calculating the display value based on inserting a temporary DOM element: https://github.com/fabiospampinato/cash/blob/1c1b316e53cc3322e417a93a0e7c4745852796d0/dist/cash.ts

**Comment by vitmalina** [comment]
Good catch. Agree
